"use client";

import { themes } from "@/themes";
import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider } from "@chakra-ui/react";
import { extendTheme } from "@chakra-ui/react";

type RootLayoutType = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutType) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>
          <ChakraProvider theme={themes}>{children}</ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
